version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongoVolume:/data/db
  
  backend22: 
    image: backend22
    container_name: backend_container
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongo_container:27017"
  
volumes:
  mongoVolume: